#!/usr/bin/env python3
import os,re,json,hashlib,random,pathlib
ROOT=pathlib.Path(__file__).resolve().parents[3]
CFILE=ROOT/"research/interventions/20260926/r77_h1_pa7_control_r1/R77_H1_PA7_CONTROL_R4_FULL_SCREENPLAY.txt"
TFILE=ROOT/"research/interventions/20260926/r77_h1_pa7_treatment_r1/R77_H1_PA7_TREATMENT_R3_FINAL_SCREENPLAY.txt"
OUT=ROOT/"pa7_external_dispatch"
OUT.mkdir(exist_ok=True)

CONTROL=CFILE.read_text(encoding="utf-8")
TREATMENT=TFILE.read_text(encoding="utf-8")
CSHA=hashlib.sha256(CONTROL.encode()).hexdigest()
TSHA=hashlib.sha256(TREATMENT.encode()).hexdigest()
assert CSHA=="41f45e7d00dbd9e4a89837cac0c7516c18c5f42fd1edd066015f824f27d36495"
assert TSHA=="001571fd5ff9b7998a973ced39efa3957ebe515aa06fa8b295c5c2f47cb641ec"

WHOLE=[
"EPISODE_PREMISE_COHERENCE","CAUSAL_SEQUENCE_PROGRESSION","THREAD_AND_SUBPLOT_INTEGRATION",
"CHARACTER_RELATIONSHIP_TRAJECTORY","INFORMATION_TOPOLOGY_DRAMATIZATION",
"SCENE_NECESSITY_AND_DISTINCT_FUNCTION","ESCALATION_PACING","CLOSURE_DEFERRED_BALANCE"]
SURFACE=[
"DIALOGUE_SUBTEXT","CHARACTER_VOICE","RELATIONSHIP_STATUS_PRESSURE","PHYSICALIZATION_ACTION",
"PACING_ESCALATION_TIME_PRESSURE","ENSEMBLE_WORLD_SPECIFICITY","INFORMATION_DRAMATIZATION",
"KOREAN_SPOKEN_NATURALNESS","SCENE_OPENING_VISUALIZATION","PERFORMANCE_DIRECTION_QUALITY",
"ACTION_DIALOGUE_BINDING","EMOTION_EXTERNALIZATION","CINEMATIC_READABILITY","DIRECTION_DETAIL_ECONOMY"]
SCENES=[5,12,21,29,38,46]
CRIT=[
"INTERNAL_SCHEMA_OR_RESEARCH_META_LEAK","IMPORTANT_STATE_CHANGE_WITHOUT_SCREEN_VISIBLE_CARRIER",
"EXPOSITORY_EMOTION_STATE_DIALOGUE_AS_DOMINANT_CRAFT","SEVERE_CHARACTER_VOICE_COLLAPSE",
"MAJOR_CAUSAL_OR_CONTINUITY_BREAK","DIRECTION_BLOAT_THAT_REPEATS_DIALOGUE_OR_STATE"]

def extract(txt):
    ms=list(re.finditer(r"(?m)^씬\s+(\d+)\.\s*[^\n]*$",txt))
    out={}
    for i,m in enumerate(ms):
        end=ms[i+1].start() if i+1<len(ms) else len(txt)
        out[int(m.group(1))]=txt[m.start():end].strip()
    return out
C_SC=extract(CONTROL); T_SC=extract(TREATMENT)
assert sorted(C_SC)==list(range(1,51))
assert sorted(T_SC)==list(range(1,51))

instruction="""You are an independent blind evaluator of two complete Korean broadcast-drama screenplay realizations labeled SCRIPT A and SCRIPT B.

INDEPENDENCE
- Use only this packet.
- Do not search any project repository, prior conversation, hidden plan, model identity, system lineage, internal score, or another evaluator's output.
- Do not infer which script is newer, older, experimental, preferred, or generated by a particular system.
- Evaluate the finished screenplay text only.
- Preserve your first complete schema-valid judgment.

WHOLE EPISODE
Score A and B independently from 1 to 10 on every WHOLE_EPISODE_AXIS.

PRE-FROZEN SCENE SAMPLE
For SC05, SC12, SC21, SC29, SC38, SC46, score each script 1 to 10 on every SURFACE_AXIS.

Interpretation:
- DIALOGUE_SUBTEXT: pressure, evasion, negotiation, withholding or choice rather than direct state explanation.
- CHARACTER_VOICE: distinct diction, sentence shape, directness, humor, avoidance pattern, role logic and conflict strategy.
- PHYSICALIZATION_ACTION: important changes carried by playable action, gaze/expression, hands, props, blocking, silence, failed action or spatial change.
- PERFORMANCE_DIRECTION_QUALITY: playable actor behavior and emotional flow rather than abstract emotion labels.
- ACTION_DIALOGUE_BINDING: speech changes or is changed by simultaneous action.
- EMOTION_EXTERNALIZATION: emotion inferable from behavior/performance rather than explained directly.
- DIRECTION_DETAIL_ECONOMY: enough to stage but not redundant with dialogue or theme.

OUTPUT-ONLY RECONSTRUCTION
For A and B independently reconstruct only from the screenplay:
episode premise; major threads; functional sequence progression; relationship trajectories; resolved due-now material; deferred/open material.
Mark each reconstructed item EVIDENCED or INFERRED.

CRITICAL VIOLATIONS
Flag only clearly evidenced violations from the supplied labels and cite scenes.

PAIRED PREFERENCE
Choose A, B, or TIE separately for whole_episode_preference and surface_craft_preference. Explain with concrete screenplay evidence.

Return JSON only using the supplied output schema.
"""

schema={
 "judge_id":"J01",
 "scripts":{
  "A":{
   "whole_episode_scores":{a:0 for a in WHOLE},
   "scene_scores":{f"SC{x:02d}":{a:0 for a in SURFACE} for x in SCENES},
   "reconstruction":{"episode_premise":[],"major_threads":[],"sequence_functions":[],"relationship_trajectories":[],"resolved_due_now":[],"deferred_open":[]},
   "critical_violations":[],"strengths":[],"weaknesses":[]
  },
  "B":{
   "whole_episode_scores":{a:0 for a in WHOLE},
   "scene_scores":{f"SC{x:02d}":{a:0 for a in SURFACE} for x in SCENES},
   "reconstruction":{"episode_premise":[],"major_threads":[],"sequence_functions":[],"relationship_trajectories":[],"resolved_due_now":[],"deferred_open":[]},
   "critical_violations":[],"strengths":[],"weaknesses":[]
  }
 },
 "paired":{"whole_episode_preference":"A|B|TIE","surface_craft_preference":"A|B|TIE","paired_reasoning_evidence":[]},
 "overall_notes":""
}

rng=random.SystemRandom()
judges=["J01","J02","J03"]
positions=["A","A","B"]
rng.shuffle(positions)
mapping={j:{"treatment_position":p,"control_position":"B" if p=="A" else "A"} for j,p in zip(judges,positions)}

for j in judges:
    d=OUT/j; d.mkdir(parents=True,exist_ok=True)
    tpos=mapping[j]["treatment_position"]
    A=TREATMENT if tpos=="A" else CONTROL
    B=CONTROL if tpos=="A" else TREATMENT
    Asc=T_SC if tpos=="A" else C_SC
    Bsc=C_SC if tpos=="A" else T_SC
    packet=instruction
    packet+="\n\nWHOLE_EPISODE_AXES\n"+"\n".join(WHOLE)
    packet+="\n\nSURFACE_AXES\n"+"\n".join(SURFACE)
    packet+="\n\nCRITICAL_VIOLATIONS\n"+"\n".join(CRIT)
    packet+="\n\n================ SCRIPT A ================\n\n"+A
    packet+="\n\n================ SCRIPT B ================\n\n"+B
    packet+="\n\n================ PRE-FROZEN SCENE SAMPLE: SCRIPT A ================\n"
    for sc in SCENES: packet+=f"\n\n--- A SC{sc:02d} ---\n{Asc[sc]}"
    packet+="\n\n================ PRE-FROZEN SCENE SAMPLE: SCRIPT B ================\n"
    for sc in SCENES: packet+=f"\n\n--- B SC{sc:02d} ---\n{Bsc[sc]}"
    forbidden=["Treatment","Control","PA7","R77","focus axis","provider-analog",TSHA,CSHA,"PLANNING_ARTIFACT","STATE_LEDGER"]
    hits=[x for x in forbidden if x.lower() in packet.lower()]
    if hits: raise SystemExit(f"blind leak {j}: {hits}")
    (d/f"{j}_BLIND_PACKET.txt").write_text(packet,encoding="utf-8")
    sch=json.loads(json.dumps(schema)); sch["judge_id"]=j
    (d/f"{j}_OUTPUT_SCHEMA.json").write_text(json.dumps(sch,ensure_ascii=False,indent=2),encoding="utf-8")
    manifest={
      "schema":"PA7_BLIND_JUDGE_PACKET_MANIFEST_R1","judge_id":j,
      "packet_sha256":hashlib.sha256(packet.encode()).hexdigest(),"packet_chars":len(packet),
      "prefrozen_scenes":SCENES,"mapping_present":False,"forbidden_hit_count":0
    }
    (d/f"{j}_PACKET_MANIFEST.json").write_text(json.dumps(manifest,ensure_ascii=False,indent=2),encoding="utf-8")

coord={
 "schema":"R77_H1_PA7_COORDINATOR_MAPPING_R1","date":"2026-09-26",
 "mapping":mapping,"treatment_surface_sha256":TSHA,"control_surface_sha256":CSHA,
 "reveal_rule":"Do not reveal until all three first schema-valid raw judgments are hash-sealed."
}
(OUT/"COORDINATOR_MAPPING_R1.json").write_text(json.dumps(coord,ensure_ascii=False,indent=2),encoding="utf-8")
receipt={"schema":"R77_H1_PA7_DISPATCH_BUILD_RECEIPT_R1","status":"PASS__3_BLIND_PACKETS__LEAK_0","judge_packet_hashes":{},"mapping_artifact_present":True}
for j in judges:
    mf=json.loads((OUT/j/f"{j}_PACKET_MANIFEST.json").read_text(encoding="utf-8"))
    receipt["judge_packet_hashes"][j]=mf["packet_sha256"]
(OUT/"DISPATCH_BUILD_RECEIPT_R1.json").write_text(json.dumps(receipt,ensure_ascii=False,indent=2),encoding="utf-8")
print(json.dumps(receipt,ensure_ascii=False,sort_keys=True))
